// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Address.sol";

/**
 * @title AppleAMM
 * @notice Constant product AMM (x * y = k) for APPL/ETH pair
 * @dev 0.30% fee (30 bps) on all swaps, fee remains in pool
 *
 * Key mechanics:
 * - Liquidity providers deposit both APPL and ETH in proportion to current reserves
 * - LP tokens track pro-rata share of the pool
 * - Swaps maintain the x*y=k invariant (minus fees)
 * - Fees accumulate in the pool, benefiting all LPs
 *
 * SYSTEM CONNECTIONS:
 * - Deployed by: scripts/deploy.sh via contracts/script/Deploy.s.sol
 * - Go binding: backend/internal/contracts/apple_amm.go (generated by scripts/generate-bindings.sh)
 * - Backend executor: backend/internal/engine/executor.go calls swapETHForApples, swapApplesForETH,
 *   getReserves, getSpotPrice, getTotalFees
 * - Bot consumers: whale, retail, meanrev bots call executor swap methods
 * - Frontend reads: reserves and spot price are polled every 2s by backend (cmd/simulator/main.go),
 *   broadcast via WebSocket to frontend components (PriceChart, LPStats, ImpactCurve)
 * - Events (LogSwap) are parsed by executor.go to build Trade structs
 *   which flow to the frontend Blotter and KeyEvents components
 */
contract AppleAMM is ReentrancyGuard {
    using SafeERC20 for IERC20;
    
    // ============================================================
    // CUSTOM ERRORS
    // ============================================================
    
    error InsufficientLiquidity();
    error InsufficientAPPLLiquidity();
    error InsufficientETHLiquidity();
    error PoolEmpty();
    error InvalidTokenAddress();
    error AmountMustBePositive();
    error InsufficientLPTokens();
    error InsufficientOutput();
    error SlippageExceeded();
    error InsufficientInputAmount();
    
    // ============================================================
    // CONSTANTS
    // ============================================================
    
    uint256 private constant PRICE_SCALE = 1e18;
    
    // Fee: 0.30% = 30 bps = 30/10000
    uint256 public constant FEE_NUMERATOR = 30;
    uint256 public constant FEE_DENOMINATOR = 10000;
    
    // ============================================================
    // STATE
    // ============================================================
    
    IERC20 public immutable appleToken;
    
    // Pool reserves
    uint256 public appleReserve;
    uint256 public ethReserve;
    
    // LP token accounting (simplified, no ERC20)
    uint256 public totalLPTokens;
    mapping(address => uint256) public lpBalances;
    
    // Track fees for metrics
    uint256 public totalFeesApple;
    uint256 public totalFeesETH;
    
    // ============================================================
    // EVENTS
    // ============================================================
    
    event LogSwap(
        address indexed trader,
        bool isBuy,              // true = buying APPL with ETH
        uint256 amountIn,
        uint256 amountOut,
        uint256 price,           // price after swap (scaled by 1e18)
        uint256 fee,
        uint256 timestamp
    );
    
    event LogLiquidityAdded(
        address indexed provider,
        uint256 appleAmount,
        uint256 ethAmount,
        uint256 lpTokens
    );
    
    event LogLiquidityRemoved(
        address indexed provider,
        uint256 appleAmount,
        uint256 ethAmount,
        uint256 lpTokens
    );
    
    // ============================================================
    // CONSTRUCTOR
    // ============================================================
    
    constructor(address _appleToken) {
        if (_appleToken == address(0)) revert InvalidTokenAddress();
        appleToken = IERC20(_appleToken);
    }
    
    // ============================================================
    // LIQUIDITY FUNCTIONS
    // ============================================================
    
    /**
     * @notice Add liquidity to the pool
     * @param appleAmount Amount of APPL tokens to deposit
     * @return lpTokens Amount of LP tokens minted to the provider
     * 
     * @dev First deposit sets the initial ratio using geometric mean (sqrt(x*y)).
     *      Subsequent deposits must maintain the current reserve ratio.
     *      ETH is sent as msg.value and must match the APPL/ETH ratio.
     *      LP tokens represent pro-rata share of the pool.
     */
    function addLiquidity(uint256 appleAmount) external payable nonReentrant returns (uint256 lpTokens) {
        if (appleAmount == 0 || msg.value == 0) revert AmountMustBePositive();
        
        // Transfer APPL from sender
        appleToken.safeTransferFrom(msg.sender, address(this), appleAmount);
        
        if (totalLPTokens == 0) {
            // First deposit: LP tokens = sqrt(appleAmount * ethAmount)
            // Using geometric mean to prevent manipulation
            lpTokens = sqrt(appleAmount * msg.value);
            if (lpTokens == 0) revert InsufficientLiquidity();
        } else {
            // Subsequent deposits: maintain ratio
            // LP tokens proportional to contribution
            uint256 lpFromApple = (appleAmount * totalLPTokens) / appleReserve;
            uint256 lpFromETH = (msg.value * totalLPTokens) / ethReserve;
            
            // Use minimum to prevent gaming
            lpTokens = lpFromApple < lpFromETH ? lpFromApple : lpFromETH;
            if (lpTokens == 0) revert InsufficientLiquidity();
        }
        
        // Update state
        appleReserve += appleAmount;
        ethReserve += msg.value;
        totalLPTokens += lpTokens;
        lpBalances[msg.sender] += lpTokens;
        
        emit LogLiquidityAdded(msg.sender, appleAmount, msg.value, lpTokens);
    }
    
    /**
     * @notice Remove liquidity from the pool
     * @param lpTokenAmount Amount of LP tokens to burn
     * @return appleOut Amount of APPL tokens returned to provider
     * @return ethOut Amount of ETH returned to provider
     * 
     * @dev Returns pro-rata share of both reserves based on LP token amount.
     *      State is updated before transfers to prevent reentrancy.
     */
    function removeLiquidity(uint256 lpTokenAmount) external nonReentrant returns (uint256 appleOut, uint256 ethOut) {
        if (lpTokenAmount == 0) revert AmountMustBePositive();
        if (lpBalances[msg.sender] < lpTokenAmount) revert InsufficientLPTokens();
        
        // Calculate pro-rata share
        appleOut = (lpTokenAmount * appleReserve) / totalLPTokens;
        ethOut = (lpTokenAmount * ethReserve) / totalLPTokens;
        
        if (appleOut == 0 || ethOut == 0) revert InsufficientOutput();
        
        // Update state BEFORE transfers (reentrancy protection)
        lpBalances[msg.sender] -= lpTokenAmount;
        totalLPTokens -= lpTokenAmount;
        appleReserve -= appleOut;
        ethReserve -= ethOut;
        
        // Transfer assets
        appleToken.safeTransfer(msg.sender, appleOut);
        Address.sendValue(payable(msg.sender), ethOut);
        
        emit LogLiquidityRemoved(msg.sender, appleOut, ethOut, lpTokenAmount);
    }
    
    // ============================================================
    // SWAP FUNCTIONS
    // ============================================================
    
    /**
     * @notice Swap ETH for APPL (buy APPL)
     * @param minApples Minimum APPL tokens to receive (slippage protection)
     * @return applesOut Amount of APPL tokens received
     * 
     * @dev ETH is sent as msg.value. A 0.30% fee is deducted before calculating output.
     *      Reverts if output is less than minApples or pool lacks liquidity.
     */
    function swapETHForApples(uint256 minApples) external payable nonReentrant returns (uint256 applesOut) {
        if (msg.value == 0) revert AmountMustBePositive();
        _validatePoolNotEmpty();
        
        // Calculate fee and amount after fee
        (uint256 fee, uint256 amountInWithFee) = _calculateSwapFee(msg.value);
        
        // Calculate output amount
        applesOut = getAmountOut(amountInWithFee, ethReserve, appleReserve);
        if (applesOut < minApples) revert SlippageExceeded();
        if (applesOut >= appleReserve) revert InsufficientAPPLLiquidity();
        
        // Execute swap
        _executeSwap(true, msg.value, applesOut, fee);
        
        return applesOut;
    }
    
    /**
     * @notice Swap APPL for ETH (sell APPL)
     * @param appleAmount Amount of APPL tokens to sell
     * @param minETH Minimum ETH to receive (slippage protection)
     * @return ethOut Amount of ETH received
     * 
     * @dev APPL tokens are transferred from caller. A 0.30% fee is deducted before calculating output.
     *      Reverts if output is less than minETH or pool lacks liquidity.
     */
    function swapApplesForETH(uint256 appleAmount, uint256 minETH) external nonReentrant returns (uint256 ethOut) {
        if (appleAmount == 0) revert AmountMustBePositive();
        _validatePoolNotEmpty();
        
        // Transfer APPL from seller
        appleToken.safeTransferFrom(msg.sender, address(this), appleAmount);
        
        // Calculate fee and amount after fee
        (uint256 fee, uint256 amountInWithFee) = _calculateSwapFee(appleAmount);
        
        // Calculate output amount
        ethOut = getAmountOut(amountInWithFee, appleReserve, ethReserve);
        if (ethOut < minETH) revert SlippageExceeded();
        if (ethOut >= ethReserve) revert InsufficientETHLiquidity();
        
        // Execute swap
        _executeSwap(false, appleAmount, ethOut, fee);
        
        return ethOut;
    }
    
    // ============================================================
    // VIEW FUNCTIONS
    // ============================================================
    
    /**
     * @notice Get current pool reserves
     * @return _appleReserve Current APPL token reserve in the pool
     * @return _ethReserve Current ETH reserve in the pool
     */
    function getReserves() external view returns (uint256 _appleReserve, uint256 _ethReserve) {
        return (appleReserve, ethReserve);
    }
    
    /**
     * @notice Get current spot price (ETH per APPL, scaled by PRICE_SCALE)
     * @return price Price in wei of ETH per 1 APPL
     * @dev Returns ethReserve * PRICE_SCALE / appleReserve
     */
    function getSpotPrice() public view returns (uint256 price) {
        if (appleReserve == 0) return 0;
        return (ethReserve * PRICE_SCALE) / appleReserve;
    }
    
    /**
     * @notice Calculate output amount for a given input (constant product formula)
     * @param amountIn Input amount (after fee deduction)
     * @param reserveIn Reserve of input token
     * @param reserveOut Reserve of output token
     * @return amountOut Output amount
     * @dev Uses x * y = k formula
     *      amountOut = (amountIn * reserveOut) / (reserveIn + amountIn)
     */
    function getAmountOut(
        uint256 amountIn,
        uint256 reserveIn,
        uint256 reserveOut
    ) public pure returns (uint256 amountOut) {
        if (amountIn == 0) revert InsufficientInputAmount();
        if (reserveIn == 0 || reserveOut == 0) revert InsufficientLiquidity();
        
        // Constant product formula: x * y = k
        // newReserveIn = reserveIn + amountIn
        // newReserveOut = k / newReserveIn = (reserveIn * reserveOut) / (reserveIn + amountIn)
        // amountOut = reserveOut - newReserveOut = (amountIn * reserveOut) / (reserveIn + amountIn)
        
        uint256 numerator = amountIn * reserveOut;
        uint256 denominator = reserveIn + amountIn;
        amountOut = numerator / denominator;
    }
    
    /**
     * @notice Get LP token balance for an address
     * @param account Address to query LP token balance for
     * @return balance LP token balance of the account
     */
    function getLPBalance(address account) external view returns (uint256 balance) {
        return lpBalances[account];
    }
    
    /**
     * @notice Get total fees collected since contract deployment
     * @return feesApple Total APPL fees collected (from sell swaps)
     * @return feesETH Total ETH fees collected (from buy swaps)
     */
    function getTotalFees() external view returns (uint256 feesApple, uint256 feesETH) {
        return (totalFeesApple, totalFeesETH);
    }
    
    // ============================================================
    // INTERNAL HELPER FUNCTIONS
    // ============================================================
    
    /**
     * @notice Calculate swap fee and amount after fee
     * @param amountIn Input amount
     * @return fee Fee amount
     * @return amountInWithFee Amount after fee deduction
     */
    function _calculateSwapFee(uint256 amountIn) internal pure returns (uint256 fee, uint256 amountInWithFee) {
        fee = (amountIn * FEE_NUMERATOR) / FEE_DENOMINATOR;
        amountInWithFee = amountIn - fee;
    }
    
    /**
     * @notice Execute swap: update reserves, transfer tokens, emit event
     * @param isBuy True if buying APPL with ETH, false if selling APPL for ETH
     * @param amountIn Input amount (full amount including fee)
     * @param amountOut Output amount
     * @param fee Fee amount
     */
    function _executeSwap(bool isBuy, uint256 amountIn, uint256 amountOut, uint256 fee) internal {
        // Update reserves
        if (isBuy) {
            ethReserve += amountIn;  // Full amount including fee
            appleReserve -= amountOut;
            totalFeesETH += fee;
            // Transfer APPL to buyer
            appleToken.safeTransfer(msg.sender, amountOut);
        } else {
            appleReserve += amountIn;  // Full amount including fee
            ethReserve -= amountOut;
            totalFeesApple += fee;
            // Transfer ETH to seller
            Address.sendValue(payable(msg.sender), amountOut);
        }
        
        // Emit swap event
        emit LogSwap(
            msg.sender,
            isBuy,
            amountIn,
            amountOut,
            getSpotPrice(),
            fee,
            block.timestamp
        );
    }
    
    /**
     * @notice Validate that pool has liquidity
     */
    function _validatePoolNotEmpty() internal view {
        if (appleReserve == 0 || ethReserve == 0) revert PoolEmpty();
    }
    
    /**
     * @notice Calculate square root using Babylonian method
     * @param x Value to take square root of
     * @return y Square root of x
     */
    function sqrt(uint256 x) internal pure returns (uint256 y) {
        if (x == 0) return 0;
        
        uint256 z = (x + 1) / 2;
        y = x;
        while (z < y) {
            y = z;
            z = (x / z + z) / 2;
        }
    }
    
    // Allow contract to receive ETH
    receive() external payable {}
}
