// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title AppleToken
 * @notice Simple ERC20 token for AMM simulation
 * @dev Owner can mint tokens for initial distribution.
 *
 * SYSTEM CONNECTIONS:
 * - Deployed by: scripts/deploy.sh via contracts/script/Deploy.s.sol
 * - Minted to: All 30 Anvil accounts during deployment (see Deploy.s.sol:mintTokens)
 * - Go binding: backend/internal/contracts/apple_token.go (generated by scripts/generate-bindings.sh)
 * - Used by backend: executor.go calls approve/transfer before AMM sell swaps
 * - AppleAMM holds: APPL tokens as pool reserves (transferred during addLiquidity and swaps)
 */
contract AppleToken is ERC20, Ownable {
    constructor() ERC20("Apple", "APPL") Ownable(msg.sender) {}
    
    /**
     * @notice Mint tokens to an address
     * @param to Recipient address
     * @param amount Amount to mint (in wei)
     */
    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }
}
